name: "Daily tests"
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false
      ddev_version:
        type: string
        description: DDEV version to test
        required: false
        default: '["stable"]'
      test_type:
        type: string
        description: Test type to run. Can be "local" or "release"
        required: false
        default: "release"
  schedule:
    - cron: "25 08 * * *"

jobs:
  run_tests:
    name: Run tests
    uses: oblakstudio/public-workflows/.github/workflows/ddev-test_addon.yaml@v1
    secrets: inherit
    with:
      ddev_version: '["stable", "HEAD", "edge"]'
      test_type: "release"
  keep-the-job-alive:
    name: Keep the job alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@1.2.2
        with:
          commit_message: "chore(cron): Keepalive workflow [skip ci]"
